export const cinema = [
  {
    theme: "cinema",
    question: "Which actor played the character Jack Dawson in the 1997 movie Titanic?",
    a_option: "Leonardo DiCaprio",
    b_option: "Tom Hanks",
    c_option: "Brad Pitt",
    d_option: "Johnny Depp",
    correctOption: "a_option",
  },
  {
    theme: "cinema",
    question: "In the movie Finding Nemo, what type of fish is Nemo?",
    a_option: "Seahorse",
    b_option: "Angelfish",
    c_option: "Surgeonfish",
    d_option: "Clownfish",
    correctOption: "d_option",
  },
  {
    theme: "cinema",
    question: "Which actor portrayed the character Iron Man in the Marvel Cinematic Universe?",
    a_option: "Chris Evans",
    b_option: "Mark Ruffalo",
    c_option: "Robert Downey Jr.",
    d_option: "Chris Hemsworth",
    correctOption: "c_option",
  },
  {
    theme: "cinema",
    question: "In which movie does Arnold Schwarzenegger's character say the famous line 'Hasta la vista, baby'?",
    a_option: "The Terminator",
    b_option: "Rambo",
    c_option: "Die Hard",
    d_option: "Predator",
    correctOption: "a_option",
  },
  {
    theme: "cinema",
    question: "Which film features a young lion prince named Simba and his journey to reclaim his kingdom?",
    a_option: "Madagascar",
    b_option: "The Lion King",
    c_option: "Tarzan",
    d_option: "Aladdin",
    correctOption: "b_option",
  },
];

export const sports = [
  {
    theme: "sports",
    question: "How many players make up a soccer team on the field during a match?",
    a_option: "9",
    b_option: "12",
    c_option: "10",
    d_option: "11",
    correctOption: "d_option",
  },
  {
    theme: "sports",
    question: "How many holes typically make up a standard golf course?",
    a_option: "9",
    b_option: "12",
    c_option: "18",
    d_option: "21",
    correctOption: "c_option",
  },
  {
    theme: "sports",
    question: "Which sport is known as the world's most popular sport?",
    a_option: "Basketball",
    b_option: "Cricket",
    c_option: "Soccer",
    d_option: "Tennis",
    correctOption: "c_option",
  },
  {
    theme: "sports",
    question: "What year was the first world cup?",
    a_option: "1896",
    b_option: "1898",
    c_option: "1892",
    d_option: "1894",
    correctOption: "a_option",
  },
  {
    theme: "sports",
    question: "What year was the first world cup?",
    a_option: "1934",
    b_option: "1930",
    c_option: "1940",
    d_option: "1938",
    correctOption: "b_option",
  },
];

export const tech = [
  {
    theme: "tech",
    question: "What is the name of Amazon's virtual assistant?",
    a_option: "Siri",
    b_option: "Cortana",
    c_option: "Google Assistant",
    d_option: "Alexa",
    correctOption: "b_option",
  },
  {
    theme: "tech",
    question: "What is the most widely used operating system in the world for personal computers?",
    a_option: "Windows",
    b_option: "macOS",
    c_option: "Linux",
    d_option: "Android",
    correctOption: "a_option",
  },
  {
    theme: "tech",
    question: "Which wireless technology is used to transfer data over short distances between devices?",
    a_option: "LTE",
    b_option: "Wi-Fi",
    c_option: "NFC",
    d_option: "Bluetooth",
    correctOption: "d_option",
  },
  {
    theme: "tech",
    question: "What does 'www' mean?",
    a_option: "World Wide Web",
    b_option: "Webpage Without Words",
    c_option: "Wide Width Wavelength",
    d_option: "World Wired Web",
    correctOption: "a_option",
  },
  {
    theme: "tech",
    question: "Which of these is an open-source operating system?",
    a_option: "Windows",
    b_option: "macOS",
    c_option: "Linux",
    d_option: "iOS",
    correctOption: "c_option",
  },
];

export const science = [
  {
    theme: "science",
    question: "What is the basic unit of life?",
    a_option: "Atom",
    b_option: "Molecule",
    c_option: "Cell",
    d_option: "Organism",
    correctOption: "c_option",
  },
  {
    theme: "science",
    question: "What is the longest bone in the human body?",
    a_option: "Skull",
    b_option: "Femur",
    c_option: "Rib",
    d_option: "Humerus",
    correctOption: "b_option",
  },
  {
    theme: "science",
    question: "Which gas is essential for the photosynthesis?",
    a_option: "Carbon dioxide",
    b_option: "Oxygen",
    c_option: "Nitrogen",
    d_option: "Hydrogen",
    correctOption: "a_option",
  },
  {
    theme: "science",
    question: "What is the force that pulls objects toward the center of the Earth?",
    a_option: "Gravity",
    b_option: "Magnetism",
    c_option: "Centrifugal force",
    d_option: "Repulsion force",
    correctOption: "a_option",
  },
  {
    theme: "science",
    question: "What is the part of the eye that controls the amount of light entering?",
    a_option: "Retina",
    b_option: "Lens",
    c_option: "Cornea",
    d_option: "Iris",
    correctOption: "d_option",
  },
];

export const math = [
  {
    theme: "math",
    question: "How much is 2^5",
    a_option: "7",
    b_option: "32",
    c_option: "30",
    d_option: "10",
    correctOption: "b_option",
  },
  {
    theme: "math",
    question: "How much is half of 100?",
    a_option: "25",
    b_option: "75",
    c_option: "50",
    d_option: "100",
    correctOption: "c_option",
  },
  {
    theme: "math",
    question: "What is the next number in the sequence: 1, 3, 5, ...?",
    a_option: "6",
    b_option: "9",
    c_option: "8",
    d_option: "7",
    correctOption: "d_option",
  },
  {
    theme: "math",
    question: "How much is 7+3x2",
    a_option: "13",
    b_option: "16",
    c_option: "20",
    d_option: "23",
    correctOption: "a_option",
  },
  {
    theme: "math",
    question: "How much is √169",
    a_option: "14",
    b_option: "13",
    c_option: "11",
    d_option: "12",
    correctOption: "b_option",
  },
];

export const knowledge = [
  {
    theme: "knowledge",
    question: "Which animal is known for its long trunk?",
    a_option: "Elephant",
    b_option: "Giraffe",
    c_option: "Lion",
    d_option: "Rhinoceros",
    correctOption: "a_option",
  },
  {
    theme: "knowledge",
    question: "What is the largest ocean in the world?",
    a_option: "Indian Ocean",
    b_option: "Pacific Ocean",
    c_option: "Atlantic Ocean",
    d_option: "Arctic Ocean",
    correctOption: "b_option",
  },
  {
    theme: "knowledge",
    question: "What is the chemical symbol for gold?",
    a_option: "Gd",
    b_option: "Gl",
    c_option: "Ag",
    d_option: "Au",
    correctOption: "d_option",
  },
  {
    theme: "knowledge",
    question: "What is the capital of the United States of America?",
    a_option: "New York",
    b_option: "Washington, D.C",
    c_option: "Los Angeles",
    d_option: "Chicago",
    correctOption: "b_option",
  },
  {
    theme: "knowledge",
    question: "What is the largest country in the world?",
    a_option: "USA",
    b_option: "Russia",
    c_option: "China",
    d_option: "Brazil",
    correctOption: "c_option",
  },
];

export const music = [
  {
    theme: "music",
    question: "Which band is known as 'The Fab Four'?",
    a_option: "The Rolling Stones",
    b_option: "The Beatles",
    c_option: "Queen",
    d_option: "Led Zeppelin",
    correctOption: "b_option",
  },
  {
    theme: "music",
    question: "Which musical instrument is associated with Mozart?",
    a_option: "Violin",
    b_option: "Flute",
    c_option: "Piano",
    d_option: "Trumpet",
    correctOption: "c_option",
  },
  {
    theme: "music",
    question: "Which singer is known as the 'Queen of Pop'?",
    a_option: "Beyoncé",
    b_option: "Madonna",
    c_option: "Lady Gaga",
    d_option: "Adele",
    correctOption: "b_option",
  },
  {
    theme: "music",
    question: "What is the best-selling album of all time?",
    a_option: "Back in Black",
    b_option: "Dark Side of the Moon",
    c_option: "Rumours",
    d_option: "Thriller",
    correctOption: "d_option",
  },
  {
    theme: "music",
    question: "Which musical genre is famous for its roots in Jamaica ",
    a_option: "Reggae",
    b_option: "Hip-hop",
    c_option: "Salsa",
    d_option: "Rock",
    correctOption: "a_option",
  },
];

export const geo = [
  {
    theme: "geo",
    question: "What is the largest planet in our solar system?",
    a_option: "Venus",
    b_option: "Earth",
    c_option: "Mars",
    d_option: "Jupiter",
    correctOption: "d_option",
  },
  {
    theme: "geo",
    question: "What instrument is used to measure earthquakes?",
    a_option: "Thermometer",
    b_option: "Barometer",
    c_option: "Seismograph",
    d_option: "Microscope",
    correctOption: "c_option",
  },
  {
    theme: "geo",
    question: "What is the longest river in the world?",
    a_option: "Nile",
    b_option: "Amazon",
    c_option: "Yangtze",
    d_option: "Mississippi",
    correctOption: "a_option",
  },
  {
    theme: "geo",
    question: "What is the largest hot desert in the world?",
    a_option: "Atacama Desert",
    b_option: "Mojave Desert",
    c_option: "Kalahari Desert",
    d_option: "Sahara Desert",
    correctOption: "d_option",
  },
  {
    theme: "geo",
    question: "What is the highest point on Earth?",
    a_option: "Denali Mountain",
    b_option: "Mount Everest",
    c_option: "Kilimanjaro Mountain",
    d_option: "Mount Fuji",
    correctOption: "b_option",
  },
];
