export const cinema = [
  {
    theme: "cinema",
    question: "What is the one taste that you cannot live without?",
    a_option: "Sour",
    b_option: "Sweet",
    c_option: "Salty",
    d_option: "Bitter",
    correctOption: "b_option",
  },
  {
    theme: "cinema",
    question: "What is the two taste that you cannot live without?",
    a_option: "Sour",
    b_option: "asdasd",
    c_option: "asdasd",
    d_option: "Bitter",
    correctOption: "b_option",
  },
  {
    theme: "cinema",
    question: "What is the one taste that you cannot live without?",
    a_option: "Sour",
    b_option: "Sweet",
    c_option: "Salty",
    d_option: "Bitter",
    correctOption: "b_option",
  },
  {
    theme: "cinema",
    question: "What is the one taste that you cannot live without?",
    a_option: "Sour",
    b_option: "Sweet",
    c_option: "Salty",
    d_option: "Bitter",
    correctOption: "b_option",
  },
  {
    theme: "cinema",
    question: "What is the one taste that you cannot live without?",
    a_option: "Sour",
    b_option: "Sweet",
    c_option: "Salty",
    d_option: "Bitter",
    correctOption: "b_option",
  },
];
